language: node_js
before_install:
# global requirements
  - make install
# local requirements
  - make update
# grunt-webfont requirements
  - sudo apt-get install fontforge
# for some test with dates
  - sudo cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

cache:
  directories:
    - bower_components
    - node_modules

notifications:
  irc: "irc.freenode.org#happyplan"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b2b8a450d30e6057c8e2
    on_success: always
    on_failure: always
    on_start: true
